included:
    - ./
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
    - Carthage
disabled_rules: # rule identifiers to exclude from running
  - type_name
  - large_tuple
  - todo
  - identifier_name
  - function_parameter_count
cyclomatic_complexity:
    warning: 20
    error: 30
function_body_length:
    warning: 75
    error: 100
file_length:
    warning: 800
    error: 1000
type_body_length:
    warning: 400
    error: 500
identifier_name:
    excluded: id # id is allowed
